### ISSUE TITLE
No result returned

### ISSUE THREAD

**Issue by saxicek** [AlessandroMinoccheri/package-info#11]
I tried to run exactly the the example as in the README.md:
```javascript
var info = require('package-info');

info('package-info', function (err, informations) {
	console.log(informations);
});
```

It returns no result.

**Comment by AlessandroMinoccheri** [comment]
Hi, I'm trying to understand the problem, as soon as possible I will fix this problem.
Thanks!

**Comment by AlessandroMinoccheri** [comment]
I have fixed the documentation, so you can use this to get information by code:

```
var info = require('package-info');

(async () => {
    console.log(await info('package-info'));
})();
```
