### ISSUE TITLE
Incorrect package.json metadata in v5.0.0

### ISSUE THREAD

**Issue by scriptex** [AlessandroMinoccheri/package-info#20]
It looks like you forgot to update the `main` and `bin` fields in your `package.json` file. 

The `main` field still points to `index.js` while there is no such file.
The `bin` field points to `src/cli.js` but you migrated the codebase to TypeScript so it's also nonexistent. 

Another issue is the lack of built JS files in the latest release - it looks like you forgot to build before publish. 

Please update the `main` and `bin` fields in the `package.json` and publish the built files 😁

**Comment by AlessandroMinoccheri** [comment]
Thanks @scriptex ! You are right, I can do it as soon as possible or it could be amazing if you would like to create a PR for this issue about `main` and `bin` files 😁

**Comment by AlessandroMinoccheri** [comment]
I have tried to fix it immediately, can you review my PR please @scriptex ? 😁

**Comment by scriptex** [comment]
I also opened a PR 😁 (maybe at the same time you did) - https://github.com/AlessandroMinoccheri/package-info/pull/22

**Comment by scriptex** [comment]
@AlessandroMinoccheri looks like you published an updated version, didn't you?
I think this one can be closed as it looks resolved.

**Comment by AlessandroMinoccheri** [comment]
Yes, it's not working again but is still ready the new one!
