### ISSUE TITLE
error getting information for got module

### ISSUE THREAD

**Issue by pnemade** [AlessandroMinoccheri/package-info#5]
Hi,
  I can use package-info binary for some modules without problem but this got module gives error. E.g.

$ package-info got
/usr/lib/node_modules/package-info/index.js:21
		var author_name = data_parsed.author.name;
		                                    ^
TypeError: Cannot read property 'name' of undefined
    at /usr/lib/node_modules/package-info/index.js:21:39
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/read-all-stream/index.js:48:6)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

**Comment by AlessandroMinoccheri** [comment]
Ok, some packages haven't author specify.
Now I have update the package with a check, and loop through maintainers if they exists.

Try now please and let me know
