### ISSUE TITLE
Uncaught error exception from got

### ISSUE THREAD

**Issue by steelbrain** [AlessandroMinoccheri/package-info#9]
<img src="https://cloud.githubusercontent.com/assets/4278113/23775038/753e8220-0548-11e7-90a4-6d698efc92a6.png">

It happened for a module that did not exist on npm. I think this package should invoke the callback with the error instead of not handling it. I'm on v2.2.3 of this package

**Comment by AlessandroMinoccheri** [comment]
Can you please tell me which package are you trying to check with package.info?
Because if I try with a not exists npm package returns me that the package doesn't exist.

**Comment by steelbrain** [comment]
@AlessandroMinoccheri I think there are two problems here, first is that you're only ever error-handling inside the callback and never `.catch()`ing the callback in case anything goes wrong inside of it.

The second problem is that the package expects certain format and doesn't validate it good enough, I experienced it with `flow-dev-tools` package

**Comment by AlessandroMinoccheri** [comment]
If you have already experienced on this problem you can create a pull request! And I'm will be very happy to accept It

**Comment by AlessandroMinoccheri** [comment]
Release new version 3.0.0 with catch callback
